### PR TITLE
Append requester to issues

### PR DESCRIPTION
**Pull request by Hampo**
Due to limitations in Overseerr, issues are raised by the owner account - this change appends the requestor to the issue description so it's obvious in the web UI. Uses Overseerr display name if it can find one, else the Discord username.

### CODE REVIEW

**Comment by thomst08** [comment]
Hey @Hampo,

That's awesome, I did think of doing this but never went about it, awesome work.

I will make sure there isn't a character limit on the message size to overseerr and make sure this is taken into account, if all good, I'll have it in the next release :)

**Comment by Hampo** [comment]
> I will make sure there isn't a character limit on the message size to overseerr and make sure this is taken into account, if all good, I'll have it in the next release :)
I checked this before even attempting to change it - Discord's own limitations set the issue description's max length to 4,000 (modal textbox limit), and I successfully raised an issue with an 8,000 character long description. The only quirk is any issue over 4,096 won't post to Discord because Overseerr doesn't trim the issue description on the modal, but that's an Overseerr problem

**Comment by thomst08** [comment]
Excellent, then in that case we should be good, I think it would be rare for an issue over 4000 characters, so even with the extra part it should reach the discord modal limit.... I hope :P

I'll test and merge it when I have a moment :)

**Comment by thomst08** [comment]
Works pretty good, awesome work.

**Pull request merged**
